# Generated by Django 4.0.2 on 2022-02-09 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('std_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentregistrationcollage',
            options={'verbose_name': 'Student Registration (HSC)', 'verbose_name_plural': 'Student Registration (HSC)'},
        ),
        migrations.AlterModelOptions(
            name='studentregistrationuni',
            options={'verbose_name': 'Student Registration (University)', 'verbose_name_plural': 'Student Registration (University)'},
        ),
        migrations.RenameField(
            model_name='result',
            old_name='course_grade',
            new_name='grade_point',
        ),
        migrations.AddField(
            model_name='enroll',
            name='enroll_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='grade_letter',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='enroll_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='payment_amount',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='payment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='financial',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationcollage',
            name='academic_status',
            field=models.CharField(choices=[('', 'Select Status'), ('running', 'Running '), ('discontinue', 'Discontinue')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationcollage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentregistrationuni',
            name='academic_status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('running', 'Running '), ('discontinue', 'Discontinue')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationuni',
            name='address',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationuni',
            name='adminsion_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationuni',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='std_portal.department'),
        ),
        migrations.AlterField(
            model_name='studentregistrationuni',
            name='nationality',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationuni',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationuni',
            name='religion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
