# Generated by Django 4.0.2 on 2022-02-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0003_rename_credit_course_course_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrationcollage',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='studentregistrationuni',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
