# Generated by Django 3.2 on 2022-02-11 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0006_rename_course_result_enroll_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financial',
            options={'verbose_name': 'Financial (University)', 'verbose_name_plural': 'Financial (University)'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Result (University)', 'verbose_name_plural': 'Result (University)'},
        ),
        migrations.AlterField(
            model_name='studentregistrationcollage',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationuni',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='FinancialCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('payment_amount', models.FloatField(default=0.0, null=True)),
                ('money_receipt_no', models.CharField(max_length=120, null=True)),
                ('comment', models.CharField(blank=True, max_length=120, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='std_portal.studentregistrationcollage')),
            ],
            options={
                'verbose_name': 'Financial (HSC)',
                'verbose_name_plural': 'Financial (HSC)',
            },
        ),
    ]
