# Generated by Django 3.2 on 2022-02-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0008_rename_financial_financialuni_delete_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentregistrationcollage',
            options={'verbose_name': 'Registration (HSC)', 'verbose_name_plural': 'Registration (HSC)'},
        ),
        migrations.AlterModelOptions(
            name='studentregistrationuni',
            options={'verbose_name': 'Registration (University)', 'verbose_name_plural': 'Registration (University)'},
        ),
        migrations.AlterField(
            model_name='studentregistrationcollage',
            name='academic_status',
            field=models.CharField(choices=[('', 'Select Status'), ('running', 'Running '), ('inactive', 'Inactive')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationuni',
            name='academic_status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('running', 'Running '), ('inactive', 'Inactive')], max_length=120, null=True),
        ),
    ]
