# Generated by Django 4.2.6 on 2023-10-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_portal', '0010_studentregistrationuni_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enroll',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='financialcollege',
            options={'ordering': ['-id'], 'verbose_name': 'Financial (HSC)', 'verbose_name_plural': 'Financial (HSC)'},
        ),
        migrations.AlterModelOptions(
            name='financialuni',
            options={'ordering': ['-id'], 'verbose_name': 'Financial (University)', 'verbose_name_plural': 'Financial (University)'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-id'], 'verbose_name': 'Result (University)', 'verbose_name_plural': 'Result (University)'},
        ),
        migrations.AlterModelOptions(
            name='studentregistrationcollage',
            options={'ordering': ['-id'], 'verbose_name': 'Registration (HSC)', 'verbose_name_plural': 'Registration (HSC)'},
        ),
        migrations.AlterModelOptions(
            name='studentregistrationuni',
            options={'ordering': ['-id'], 'verbose_name': 'Registration (University)', 'verbose_name_plural': 'Registration (University)'},
        ),
    ]
