# Generated by Django 4.0.2 on 2022-02-07 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=120, null=True)),
                ('course_code', models.CharField(max_length=120, null=True)),
                ('credit', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=120, null=True)),
                ('hod', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=150, null=True)),
                ('post_content', models.TextField(max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='notice_file/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistrationUni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=120, null=True, unique=True)),
                ('name', models.CharField(max_length=120, null=True)),
                ('email', models.CharField(max_length=120, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('fathername', models.CharField(blank=True, max_length=120, null=True)),
                ('mothername', models.CharField(blank=True, max_length=120, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('adminsion_year', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(max_length=120, null=True)),
                ('academic_status', models.CharField(choices=[('Select Status', 'Select Status'), ('Running', 'Running '), ('Discontinue', 'Select Status')], max_length=120, null=True)),
                ('religion', models.CharField(max_length=120, null=True)),
                ('nationality', models.CharField(max_length=120, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.department')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistrationCollage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=120, null=True, unique=True)),
                ('name', models.CharField(max_length=120, null=True)),
                ('email', models.CharField(max_length=120, null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('fathername', models.CharField(blank=True, max_length=120, null=True)),
                ('mothername', models.CharField(blank=True, max_length=120, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('adminsion_year', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(max_length=120, null=True)),
                ('academic_status', models.CharField(choices=[('Select Status', 'Select Status'), ('running', 'Running '), ('discontinue', 'Select Status')], max_length=120, null=True)),
                ('group', models.CharField(choices=[('Select Group', 'Select Group'), ('science', 'Science'), ('commerce', 'Business Studies / Commerce'), ('arts', 'Humanities / Arts')], max_length=120, null=True)),
                ('religion', models.CharField(max_length=120, null=True)),
                ('nationality', models.CharField(max_length=120, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_grade', models.FloatField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.studentregistrationuni')),
            ],
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=120, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.FloatField(null=True)),
                ('money_receipt_no', models.CharField(max_length=120, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.studentregistrationuni')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_year', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.studentregistrationuni')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.department'),
        ),
    ]
