# Generated by Django 3.2 on 2022-02-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, null=True)),
                ('post', models.CharField(max_length=120, null=True)),
                ('subject_taught', models.CharField(max_length=120, null=True)),
                ('educational_qualification', models.CharField(max_length=120, null=True)),
                ('university', models.CharField(max_length=120, null=True)),
                ('teacher_picture', models.ImageField(blank=True, null=True, upload_to='teacher_picture')),
            ],
        ),
    ]
