# Generated by Django 3.2 on 2022-02-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_taught',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='university',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='educational_qualification',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
