# Generated by Django 4.0.2 on 2022-02-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20220217_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistrationCollage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('notice_images', models.ImageField(blank=True, null=True, upload_to='notice_images')),
            ],
            options={
                'verbose_name': 'Image Notice',
                'verbose_name_plural': 'Image Notice',
            },
        ),
    ]
