# Generated by Django 4.0.2 on 2022-02-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_studentregistrationcollage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentRegistrationCollage',
            new_name='NoticeImages',
        ),
    ]
