"""
Django settings for ncbt project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-brum3j1#t@3ranh&^7%ma@x8uc6196-a_mrv_d-651c4%vn_$1"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    # "django.contrib.staticfiles",
    "django_cleanup.apps.CleanupConfig",
    'ckeditor',
    'ckeditor_uploader',
    "app_main",
    "std_portal",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ncbt.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "std_portal.custom_context_processor.get_profile_image",
                "app_main.custom_context_processor.miscellaneous_common_data",
            ],
        },
    },
]

WSGI_APPLICATION = "ncbt.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Dhaka"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


from .config import *

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files
if not DEBUG:
    MEDIA_ROOT = ROOT / DOMAIN_ROOT / "mediafiles"
    MEDIA_URL = "/mediafiles/"
else:
    MEDIA_ROOT = BASE_DIR / "mediafiles"
    MEDIA_URL = "/mediafiles/"


CKEDITOR_UPLOAD_PATH = "admin-uploads/"

CKEDITOR_CONFIGS = {
    "default": {
        # 'skin': 'office2013',
        # 'toolbar_Basic': [
        #     ['Source', '-', 'Bold', 'Italic']
        # ],
        "toolbar": [
            {
                "name": "document",
                "items": [
                    "Source",
                    "-",
                    "Save",
                    "NewPage",
                    "Preview",
                    "Print",
                    "-",
                    "Templates",
                ],
            },
            {
                "name": "clipboard",
                "items": [
                    "Cut",
                    "Copy",
                    "Paste",
                    "PasteText",
                    "PasteFromWord",
                    "-",
                    "Undo",
                    "Redo",
                ],
            },
            {"name": "editing", "items": ["Find", "Replace", "-", "SelectAll"]},
            {
                "name": "basicstyles",
                "items": [
                    "Bold",
                    "Italic",
                    "Underline",
                    "Strike",
                    "Subscript",
                    "Superscript",
                    "-",
                    "RemoveFormat",
                ],
            },
            {
                "name": "paragraph",
                "items": [
                    "NumberedList",
                    "BulletedList",
                    "-",
                    "Outdent",
                    "Indent",
                    "-",
                    "Blockquote",
                    "CreateDiv",
                    "-",
                    "JustifyLeft",
                    "JustifyCenter",
                    "JustifyRight",
                    "JustifyBlock",
                    "-",
                    "BidiLtr",
                    "BidiRtl",
                    "Language",
                ],
            },
            {"name": "links", "items": ["Link", "Unlink", "Anchor"]},
            {
                "name": "insert",
                "items": [
                    "Image",
                    "Flash",
                    "Table",
                    "HorizontalRule",
                    "Smiley",
                    "SpecialChar",
                    "PageBreak",
                    "Iframe",
                ],
            },
            "/",
            {"name": "styles", "items": ["Styles", "Format", "Font", "FontSize"]},
            {"name": "colors", "items": ["TextColor", "BGColor"]},
            {"name": "tools", "items": ["Maximize", "ShowBlocks"]},
            {"name": "about", "items": ["About"]},
            {
                "name": "Subtitle",
                "element": "h3",
                "styles": {"color": "#aaa", "font-style": "italic"},
            },
        ],
        # 'toolbar': 'toolbar_Basic',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        # 'height': 291,
        # 'width': '100%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        "width": "auto",
        "tabSpaces": 4,
        # 'extraPlugins': ','.join([
        #     'uploadimage',  # the upload image feature
        #     # your extra plugins here
        #     'div',
        #     'autolink',
        #     'autoembed',
        #     'embedsemantic',
        #     'autogrow',
        #     # 'devtools',
        #     'widget',
        #     'lineutils',
        #     'clipboard',
        #     'dialog',
        #     'dialogui',
        #     'elementspath'
        # ]),
    }
}
CKEDITOR_BROWSE_SHOW_DIRS = True

ADMIN_REORDER = (
    # models with custom name
    {
        "app": "app_main",
        "label": "Home",
        "models": (
            {"model": "app_main.HeaderSliderModel", "label": "Header Sliders"},
            {"model": "app_main.CounterModel", "label": "Counter"},
            {"model": "app_main.FacilityModel", "label": "Facilities"},
            {"model": "app_main.StudentActivitiesModel", "label": "Student Activities"},
            {"model": "app_main.FounderModel", "label": "Founder"},
        ),
    },
    {
        "app": "app_main",
        "label": "About",
        "models": (
            {"model": "app_main.HistoryModel", "label": "History"},
            {"model": "app_main.AboutInformationModel", "label": "About Information"},
            {"model": "app_main.CodeOfConduct", "label": "Code Of Conducts"},
        ),
    },
    {
        "app": "app_main",
        "label": "Admission",
        "models": (
            {"model": "app_main.AdmissionModel", "label": "Admission Informations"},
        ),
    },
    {
        "app": "app_main",
        "label": "Courses & routines",
        "models": (
            {"model": "app_main.CourseModel", "label": "Course"},
            {"model": "app_main.RoutineModel", "label": "Routine"},
        ),
    },
    {
        "app": "app_main",
        "label": "Notice",
        "models": (
            {"model": "app_main.Notice", "label": "Create Notice"},
        ),
    },
    {
        "app": "app_main",
        "label": "Administration",
        "models": (
            {"model": "app_main.AdministrationModel", "label": "Administration Informations"},
        ),
    },
    {
        "app": "app_main",
        "label": "Header & Footer",
        "models": (
            {"model": "app_main.FooterInformationModel", "label": "Footer & Links"},
            {"model": "app_main.ContactInformationModel", "label": "Address Informations"},
        ),
    },
    {
        "app": "app_main",
        "label": "Contact",
        "models": (
            {"model": "app_main.Contact", "label": "List of Queries"},
        ),
    },

    # Student Portal Controller

    {
        "app": "std_portal",
        "label": "Student Portal",
        "models": (
            {"model": "std_portal.StudentRegistrationUni", "label": "Honors Registration"},
            {"model": "std_portal.StudentRegistrationCollage", "label": "Collage Registration"},
            {"model": "std_portal.Department", "label": "Department"},
            {"model": "std_portal.Course", "label": "Subject"},
            {"model": "std_portal.Enroll", "label": "Enroll"},
            {"model": "std_portal.Result", "label": "Result"},
            {"model": "std_portal.FinancialUni", "label": "Financial Record for Honors"},
            {"model": "std_portal.FinancialCollege", "label": "Financial Record for Collage"},
        ),
    },

    # Reorder app models
    {"app": "auth", "label": "Users and Groups", "models": ("auth.User", "auth.Group")},
)

JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "NCBT Admin",
    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "NCBT Admin",
    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "NCBT Admin",
    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "assets/images/logo-white-circle.jpg",
    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "assets/images/default_logo.png",
    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,
    # CSS classes that are applied to the logo above
    "site_logo_classes": "",
    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "favicon/favicon-32x32.png",
    # Welcome text on the login screen
    "welcome_sign": "Welcome to the NCBT Admin",
    # Copyright on the footer
    # "copyright": "Copyright © 2023 N. CBT. All rights reserved.",
    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string
    # "search_model": ["auth.User", "auth.Group"],
    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,
    ############
    # Top Menu #
    ############
    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},
    ],
    #############
    # Side Menu #
    #############
    # Whether to display the side menu
    "show_sidebar": True,
    # Whether to aut expand the menu
    "navigation_expanded": True,
    "related_modal_active": True,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    "default_icon_parents": "fas fa-th-list",
    # "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-lightblue",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": True,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}

X_FRAME_OPTIONS = "SAMEORIGIN"
