# Generated by Django 4.2.6 on 2023-10-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_contactinformationmodel_footerinformationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerinformationmodel',
            name='details',
            field=models.TextField(max_length=500, null=True, verbose_name='Short Summary'),
        ),
    ]
