# Generated by Django 4.2.6 on 2023-10-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_headerslidermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_student', models.CharField(max_length=255, null=True, verbose_name='total students')),
                ('total_teacher', models.CharField(max_length=255, null=True, verbose_name='total teachers')),
                ('total_book', models.CharField(max_length=255, null=True, verbose_name='total books')),
                ('total_computer', models.CharField(max_length=255, null=True, verbose_name='total computers')),
            ],
        ),
    ]
