# Generated by Django 4.2.6 on 2023-10-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_foundermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=125, null=True)),
                ('details', models.TextField(blank=True, max_length=225, null=True, verbose_name='short details')),
                ('is_important', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Facility',
                'verbose_name_plural': 'Student Facilities',
            },
        ),
    ]
