# Generated by Django 4.2.6 on 2023-10-17 16:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_facilitymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, null=True, verbose_name='card title')),
                ('details', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('btn_link', models.URLField(blank=True, null=True, verbose_name='button link')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('status', models.CharField(default='editable object', editable=False, max_length=125, null=True)),
            ],
            options={
                'verbose_name': 'Student Activities',
                'verbose_name_plural': 'Student Activities',
            },
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='details',
            field=models.TextField(max_length=525, null=True, verbose_name='short details'),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='title',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
