# Generated by Django 4.2.6 on 2023-10-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_studentactivitiesmodel_alter_facilitymodel_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivitiesmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='activities-images'),
        ),
        migrations.AlterField(
            model_name='studentactivitiesmodel',
            name='status',
            field=models.CharField(default='Editable Data', editable=False, max_length=125, null=True),
        ),
    ]
