# Generated by Django 4.2.6 on 2023-10-17 17:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0010_studentactivitiesmodel_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeImages',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='post_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='post_content',
        ),
        migrations.AddField(
            model_name='notice',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='image size: w-350px x h-400', null=True, upload_to='notice-thumbnail-images'),
        ),
    ]
