# Generated by Django 4.2.6 on 2023-10-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_coursemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundermodel',
            options={'verbose_name': 'Founder', 'verbose_name_plural': 'Founder Info'},
        ),
        migrations.AddField(
            model_name='foundermodel',
            name='name',
            field=models.CharField(max_length=125, null=True, verbose_name='founder name'),
        ),
    ]
