# Generated by Django 4.2.6 on 2023-10-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_alter_foundermodel_options_foundermodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='home_cover_image',
            field=models.ImageField(blank=True, help_text='image size: w-370, h-230', null=True, upload_to='course-home-cover-images', verbose_name='course home cover image'),
        ),
    ]
