# Generated by Django 4.2.6 on 2023-10-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_routinemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinemodel',
            name='semester',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='routinemodel',
            name='year',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
