# Generated by Django 4.2.6 on 2023-10-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0014_coursemodel_home_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinformationmodel',
            options={'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Informations'},
        ),
        migrations.AddField(
            model_name='contactinformationmodel',
            name='contact_info_type',
            field=models.CharField(choices=[('', 'Select Type'), ('Main Campus', 'Main Campus'), ('Dhaka Office', 'Dhaka Office')], max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformationmodel',
            name='address',
            field=models.TextField(max_length=525, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformationmodel',
            name='details',
            field=models.TextField(max_length=325, null=True, verbose_name='contact short summary'),
        ),
        migrations.AlterField(
            model_name='contactinformationmodel',
            name='email',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformationmodel',
            name='phone',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformationmodel',
            name='work',
            field=models.CharField(max_length=225, null=True, verbose_name='working date & time'),
        ),
    ]
