# Generated by Django 4.2.6 on 2023-10-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0015_alter_contactinformationmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformationmodel',
            name='details',
            field=models.TextField(blank=True, help_text='Please provide information regarding the primary objective at the main campus.', max_length=325, null=True, verbose_name='contact short summary'),
        ),
    ]
