# Generated by Django 4.2.6 on 2023-10-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0014_routinemodel_semester_routinemodel_year'),
        ('app_main', '0016_alter_contactinformationmodel_details'),
    ]

    operations = [
    ]
