# Generated by Django 4.2.6 on 2023-10-22 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0017_merge_20231022_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinemodel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='app_main.coursemodel'),
        ),
    ]
