# Generated by Django 4.2.6 on 2023-10-23 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0017_merge_20231021_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', 'Select Administration Type'), ('Authorities', 'Authorities'), ('Teachers', 'Teachers'), ('Staffs', 'Staffs')], max_length=50, null=True)),
                ('name', models.CharField(max_length=122, null=True)),
                ('designation', models.CharField(max_length=120, null=True)),
                ('education', models.CharField(max_length=255, null=True, verbose_name='last educational qualification')),
                ('image', models.ImageField(blank=True, null=True, upload_to='administration-profile-images', verbose_name='profile picture')),
                ('active', models.BooleanField(default=True, null=True)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Administration',
                'verbose_name_plural': 'Administrations',
                'ordering': ['joining_date'],
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Query Contact', 'verbose_name_plural': 'Query Contacts'},
        ),
        migrations.AlterField(
            model_name='routinemodel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='app_main.coursemodel'),
        ),
    ]
