# Generated by Django 4.2.6 on 2023-10-22 04:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0018_alter_routinemodel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='course_article',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=999, null=True, verbose_name='course article'),
        ),
    ]
