# Generated by Django 4.2.6 on 2023-10-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0018_administrationmodel_delete_teacher_and_more'),
        ('app_main', '0019_alter_coursemodel_course_article'),
    ]

    operations = [
    ]
