# Generated by Django 4.2.6 on 2023-10-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0020_merge_20231023_2214"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="administrationmodel",
            options={
                "ordering": ["joining_date", "id"],
                "verbose_name": "Administration",
                "verbose_name_plural": "Administrations",
            },
        ),
        migrations.AddField(
            model_name="administrationmodel",
            name="show_on_home",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Show on Homepage"
            ),
        ),
        migrations.AlterField(
            model_name="coursemodel",
            name="course_article",
            field=models.TextField(
                max_length=500, null=True, verbose_name="course article"
            ),
        ),
    ]
