# Generated by Django 4.2.6 on 2023-10-24 11:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0021_alter_administrationmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=9999, null=True)),
                ('history_cover_img', models.ImageField(help_text='image size: w-800, h-500', null=True, upload_to='history-cover-image', verbose_name='history cover image')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'History',
            },
        ),
    ]
