# Generated by Django 4.2.6 on 2023-10-24 11:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0022_historymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=100, null=True, verbose_name='sub title')),
                ('title', models.CharField(max_length=150, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=999, null=True)),
                ('cover_img', models.ImageField(help_text='image size: w-800, h-500', null=True, upload_to='about-section-images', verbose_name='about section image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About InformationModel',
                'verbose_name_plural': 'About Information',
            },
        ),
    ]
