# Generated by Django 4.2.6 on 2023-10-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0023_aboutinformationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOfConduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=999, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Code Of Conduct',
                'verbose_name_plural': 'Code Of Conduct',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutinformationmodel',
            options={'verbose_name': 'About Information', 'verbose_name_plural': 'About Informations'},
        ),
    ]
