# Generated by Django 4.2.6 on 2023-10-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0020_merge_20231023_2352'),
        ('app_main', '0024_codeofconduct_alter_aboutinformationmodel_options'),
    ]

    operations = [
    ]
