# Generated by Django 4.2.6 on 2023-11-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0025_merge_20231024_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routinemodel',
            options={'verbose_name': 'Routine & Syllabus', 'verbose_name_plural': 'Routines & Syllabus'},
        ),
        migrations.AlterField(
            model_name='contactinformationmodel',
            name='address',
            field=models.TextField(max_length=999, null=True),
        ),
    ]
