# Generated by Django 4.2.6 on 2023-11-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0026_alter_routinemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contactinformationmodel',
            name='address',
            field=models.TextField(max_length=525, null=True),
        ),
    ]
