# Generated by Django 4.2.6 on 2023-11-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0027_alter_contact_address_alter_contact_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrationmodel',
            name='type',
            field=models.CharField(choices=[('', 'Select Administration Type'), ('Governing Body', 'Governing Body'), ('Teachers', 'Teachers'), ('Staffs', 'Staffs')], max_length=50, null=True),
        ),
    ]
